import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    alignItems: "center",
    height: "100%",
    width: "100%",
  },
  heading: {
    fontSize: 26,
    fontWeight: "bold",
    marginLeft: "31%",
    marginTop: "3.5%",
    marginBottom: "2%",
    color: "#000",
    textAlign: "left",
  },
  subheading: {
    fontSize: 20,
    marginLeft: "10%",
    marginTop: 20,
    marginBottom: -5,
    fontWeight: "bold",
  },
  input: {
    marginTop: "5%",
    marginLeft: "10%",
    alignItems: "center",
    height: "8%",
    width: "80%",
    borderRadius: 5,
    paddingHorizontal: 10,
    backgroundColor: "white",
    textAlign: "left",
  },
  bdayInput: {
    backgroundColor: "white",
    height: 48,
    borderRadius: 5,
    width: 200,
    alignItems: "center",
    justifyContent: "center",
    marginLeft: 20,
  },
  aboutMeInput: {
    marginTop: "5%",
    marginLeft: "10%",
    width: "80%",
    height: "16%",
    paddingVertical: 10,
    borderRadius: 5,
    paddingHorizontal: 10,
    backgroundColor: "white",
    textAlign: "left",
  },
  button: {
    backgroundColor: "#6495ED",
    borderRadius: 5,
    paddingHorizontal: 20,
    paddingVertical: 10,
    marginLeft: "30%",
    marginTop: "5%",
    width: "40%",
  },
  buttonText: {
    fontSize: 20,
    color: "white",
    textAlign: "center",
  },
  backButton: {
    position: "absolute",
    top: 0,
    left: 10,
    backgroundColor: "#transparent",
    padding: 10,
    borderRadius: 5,
  },
  backButtonText: {
    color: "#000",
    fontSize: 32,
    fontWeight: "bold",
  },
});
